# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\University\Semester 6\Software Construction and Development Lab\Project\CourseRegistered.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CourseRegistered(object):
    def setupUi(self, CourseRegistered):
        CourseRegistered.setObjectName("CourseRegistered")
        CourseRegistered.resize(690, 491)
        self.centralwidget = QtWidgets.QWidget(CourseRegistered)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginPage = QtWidgets.QWidget(self.centralwidget)
        self.LoginPage.setEnabled(True)
        self.LoginPage.setGeometry(QtCore.QRect(0, 0, 691, 471))
        self.LoginPage.setAutoFillBackground(False)
        self.LoginPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LoginPage.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LoginPage.setObjectName("LoginPage")
        self.widget_3 = QtWidgets.QWidget(self.LoginPage)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 691, 81))
        self.widget_3.setStyleSheet("background-color: rgb(66, 167, 255);")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(270, 30, 161, 31))
        self.label_2.setStyleSheet("font: 63 14pt \"Sitka Display Semibold\";\n"
                                   "background-color: rgb(66, 167, 255);\n"
                                   "")
        self.label_2.setObjectName("label_2")
        self.scrollArea = QtWidgets.QScrollArea(self.LoginPage)
        self.scrollArea.setGeometry(QtCore.QRect(310, 130, 341, 251))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.Content = QtWidgets.QWidget()
        self.Content.setGeometry(QtCore.QRect(0, 0, 339, 249))
        self.Content.setObjectName("Content")

        # Setting layout for the Content widget
        self.contentLayout = QtWidgets.QVBoxLayout(self.Content)
        self.contentLayout.setObjectName("contentLayout")

        # Content data that will be scrollable
        self.Content_Data = QtWidgets.QLabel(self.Content)
        self.Content_Data.setText("Sample text to demonstrate scrolling. " * 50)  # Sufficient text for scrolling
        self.Content_Data.setWordWrap(True)
        self.Content_Data.setObjectName("Content_Data")

        self.contentLayout.addWidget(self.Content_Data)
        self.scrollArea.setWidget(self.Content)

        self.pushButton = QtWidgets.QPushButton(self.LoginPage)
        self.pushButton.setGeometry(QtCore.QRect(10, 422, 61, 31))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.LoginPage)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 221, 251))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/dell/Downloads/Umt_logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        CourseRegistered.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CourseRegistered)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 21))
        self.menubar.setObjectName("menubar")
        CourseRegistered.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CourseRegistered)
        self.statusbar.setObjectName("statusbar")
        CourseRegistered.setStatusBar(self.statusbar)

        self.retranslateUi(CourseRegistered)
        QtCore.QMetaObject.connectSlotsByName(CourseRegistered)

    def retranslateUi(self, CourseRegistered):
        _translate = QtCore.QCoreApplication.translate
        CourseRegistered.setWindowTitle(_translate("CourseRegistered", "MainWindow"))
        self.label_2.setText(_translate("CourseRegistered", "Registered Courses"))
        self.pushButton.setText(_translate("CourseRegistered", "<<Back"))

